### PR TITLE
Map docker into the container

### PR DESCRIPTION
**Pull request by ReneHezser**
#4 
- map docker into the container
- map config readonly only

### CODE REVIEW

**Comment by IkkertSergei** [comment]
Hello Rene, thanks for your support.  The documentation and the image have been updated. You can now map the Docker client into the container.  I would close the pull request now.  PS: Currently the container does not survive the restart/stop. It seems that not all connection data is passed to the edge agent. It fails at the Connect() .  Maybe you have an idea!  :)

**Comment by ReneHezser** [comment]
Hi Sergei,
the three IoT Edge containers will not come up after a restart, because the azure-iot-edge-runtime container is not being added to the azure-iot-edge network.

docker-entrypoint.sh

    docker network create $network

results in: **network with name azure-iot-edge already exists**. As a result the edgeAgent is not able to connect to the managemen_uri and will restart.

**Comment by IkkertSergei** [comment]
Hi @ReneHezser 
thank you for your feedback. Your hint about the `docker network create` was not quite right but it has led us to a solution. So we found the restart problem and fixed it. Thank you and have fun with the image.

**Comment by ReneHezser** [comment]
I am testing on a RasperryPi 3B, because I don't have a physical Wago device.

After a restart the containers are not starting.
```
azure-iot-edge
816de269c452
Error response from daemon: network with name azure-iot-edge already exists
Error response from daemon: endpoint with name azure-iot-edge-runtime already exists in network azure-iot-edge
/docker-entrypoint.sh: line 22: export: `816de269c452': not a valid identifier
/docker-entrypoint.sh: line 22: export: `|': not a valid identifier
/docker-entrypoint.sh: line 22: export: `--raw-output': not a valid identifier
/docker-entrypoint.sh: line 22: export: `'.[].NetworkSettings.Networks."azure-iot-edge".IPAddress'': not a valid identifier
<6>2021-02-25T09:02:39Z [INFO] - Starting Azure IoT Edge Security Daemon
...
<3>2021-02-25T09:02:42Z [ERR!] - The daemon could not start up successfully: Could not start management service
<3>2021-02-25T09:02:42Z [ERR!] -        caused by: Invalid URL "http://eval:15580/"
<3>2021-02-25T09:02:42Z [ERR!] -        caused by: failed to lookup address information: Name or service not known
```

**Comment by DirkMeihoefer** [comment]
Sorry, I pushed a wrong commit. Now it should work.

**Comment by ReneHezser** [comment]
Nach einem Neustart kommen die Container jetzt wieder hoch. 🙂

Zur Info:
```
b0eaca744f0d
Error response from daemon: network with name azure-iot-edge already exists
Error response from daemon: endpoint with name azure-iot-edge-runtime already exists in network azure-iot-edge
<6>2021-02-25T10:30:46Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2021-02-25T10:30:46Z [INFO] - Version - 1.1.0
```

**Pull request closed without merging**
